version: '3.3'

services:
  app:
    image:
      build:
        context: .
        dockerfile: flask/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env

  db:
    image: 
      build:
        context: .
        dockerfile: mysql/Dockerfile
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

volumes:
  db_data: {}
