version: '3.3'

services:

  db:
    build: ./mysql/
    ports:
      - "3306:3306"
    env_file:
      - config/.env
    networks:
      - dockercompose

  app:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    networks:
      - dockercompose

networks:
  dockercompose:
